### PR TITLE
Update move-files.sh

### PR DESCRIPTION
**Pull request by stuffbymax**

### CODE REVIEW

**Comment by stuffbymax** [comment]
i am not sure but

Add Quotes Around Variables: It's a good practice to add double quotes around variables to handle cases where they might contain spaces or special characters.

Simplify File Attribute Check: Instead of using getfattr and grep, you can use the -e flag of getfattr to specify the attribute directly.

**Comment by mounta11n** [comment]
Ah thanks for the hints!

**Comment by stuffbymax** [comment]
no broblem i guess ps do you know bash well? because i need help with somthing @mounta11n

**Comment by mounta11n** [comment]
My knowledge is limited to certain areas of use cases. I can look for if I can help you with my knowledge, but I honestly often look at my bash script book or ask an LLM (GPT-4 or opus). Where exactly do you need support?

**Comment by stuffbymax** [comment]
i am making my own text editor that is made in bash and i have a some problems like i cant edit the files properly 
thanks you :)
https://github.com/stuffbymax/simple-text-editor

**Pull request merged**
